"""Add Phase 7 spatial analytics and benchmark definition schemas

Revision ID: 88be84c99bf8
Revises: 994d1425ffde
Create Date: 2026-08-17 19:21:49.123456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '88be84c99bf8'
down_revision = '994d1425ffde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('reference_name', sa.String(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_definitions_id'), 'benchmark_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_benchmark_definitions_indicator'), 'benchmark_definitions', ['indicator'], unique=True)
    
    op.create_table('spatial_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('population_count', sa.Integer(), nullable=True),
    sa.Column('population_source', sa.String(), nullable=True),
    sa.Column('population_date', sa.DateTime(), nullable=True),
    sa.Column('analysis_area_sq_km', sa.Float(), nullable=True),
    sa.Column('road_area_sq_m', sa.Float(), nullable=True),
    sa.Column('road_coverage_pct', sa.Float(), nullable=True),
    sa.Column('building_area_sq_m', sa.Float(), nullable=True),
    sa.Column('building_coverage_pct', sa.Float(), nullable=True),
    sa.Column('tree_area_sq_m', sa.Float(), nullable=True),
    sa.Column('tree_cover_pct', sa.Float(), nullable=True),
    sa.Column('water_area_sq_m', sa.Float(), nullable=True),
    sa.Column('water_cover_pct', sa.Float(), nullable=True),
    sa.Column('barren_area_sq_m', sa.Float(), nullable=True),
    sa.Column('agriculture_area_sq_m', sa.Float(), nullable=True),
    sa.Column('hospital_count', sa.Integer(), nullable=True),
    sa.Column('school_count', sa.Integer(), nullable=True),
    sa.Column('police_count', sa.Integer(), nullable=True),
    sa.Column('fire_station_count', sa.Integer(), nullable=True),
    sa.Column('hospitals_per_1000', sa.Float(), nullable=True),
    sa.Column('schools_per_1000', sa.Float(), nullable=True),
    sa.Column('infrastructure_score', sa.Float(), nullable=True),
    sa.Column('component_scores', sa.JSON(), nullable=True),
    sa.Column('formula_version', sa.String(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['imagery_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spatial_analytics_analysis_id'), 'spatial_analytics', ['analysis_id'], unique=True)
    op.create_index(op.f('ix_spatial_analytics_id'), 'spatial_analytics', ['id'], unique=False)
    
    op.drop_index('ix_urban_benchmarks_analysis_id', table_name='urban_benchmarks')
    op.drop_index('ix_urban_benchmarks_id', table_name='urban_benchmarks')
    op.drop_table('urban_benchmarks')
    
    op.add_column('imagery_analyses', sa.Column('population_count', sa.Integer(), nullable=True))
    op.add_column('imagery_analyses', sa.Column('population_source', sa.String(), nullable=True))
    op.add_column('imagery_analyses', sa.Column('population_date', sa.DateTime(), nullable=True))
    op.drop_column('imagery_analyses', 'population_estimate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imagery_analyses', sa.Column('population_estimate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('imagery_analyses', 'population_date')
    op.drop_column('imagery_analyses', 'population_source')
    op.drop_column('imagery_analyses', 'population_count')
    
    op.create_table('urban_benchmarks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('population_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('road_density_km_per_sqkm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('building_coverage_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tree_cover_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('water_cover_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('built_up_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hospitals_per_10k_pop', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('schools_per_10k_pop', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('infrastructure_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['imagery_analyses.id'], name=op.f('urban_benchmarks_analysis_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('urban_benchmarks_pkey'))
    )
    op.create_index(op.f('ix_urban_benchmarks_id'), 'urban_benchmarks', ['id'], unique=False)
    op.create_index(op.f('ix_urban_benchmarks_analysis_id'), 'urban_benchmarks', ['analysis_id'], unique=True)
    
    op.drop_index(op.f('ix_spatial_analytics_id'), table_name='spatial_analytics')
    op.drop_index(op.f('ix_spatial_analytics_analysis_id'), table_name='spatial_analytics')
    op.drop_table('spatial_analytics')
    op.drop_index(op.f('ix_benchmark_definitions_indicator'), table_name='benchmark_definitions')
    op.drop_index(op.f('ix_benchmark_definitions_id'), table_name='benchmark_definitions')
    op.drop_table('benchmark_definitions')
    # ### end Alembic commands ###
